#!/bin/bash

source public-ip-addresses

echo "Create a deployment for a flask application"
kubectl apply -f plik-deployment.yaml

#echo "Create a deployment for plik service(fixed nodeport)"
#kubectl apply -f plik-service.yaml

sleep 2
kubectl get pods -l app=plik

echo "Expose the flask application deployment using a NodePort service(--port docker-container-port)"
kubectl expose deployment plik-deployment --port 8080 --type NodePort

echo "Retrieve the node port assigned to the plik service"
export PLIK_NODE_PORT=$(kubectl get svc plik-deployment \
  --output=jsonpath='{range .spec.ports[0]}{.nodePort}')

echo "Allow remote access to plik node port"
SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
--filters "Name=tag:Name,Values=kubernetes-the-hard-way" \
--output text --query 'SecurityGroups[0].GroupId')

aws ec2 authorize-security-group-ingress \
  --group-id "${SECURITY_GROUP_ID}" \
  --protocol tcp \
  --port "${PLIK_NODE_PORT}" \
  --cidr 0.0.0.0/0

echo "Retrieve the external IP address of a worker instance"
EXTERNAL_IP=${PUBLIC_ADDRESS[worker-0]}
echo "${EXTERNAL_IP}"

echo "Make an HTTP request using the external IP address and the nginx node port"
curl -I http://"${EXTERNAL_IP}":"${PLIK_NODE_PORT}"
